kind: Pod
apiVersion: v1
metadata:
  name: busybox 
spec:
  serviceAccountName: vault
  containers:
  - image: busybox
    name: busybox
    volumeMounts:
    - name: secrets-store-inline
      mountPath: "/mnt/secrets-store"
      readOnly: true
  volumes:
    - name: secrets-store-inline
      csi:
        driver: secrets-store.csi.k8s.com
        readOnly: true
        volumeAttributes:
          providerName: "vault"
          roleName: "example-role"
          vaultAddress: "http://vault:8200"
          vaultSkipTLSVerify: "true"
          objects:  |
            array:
              - |
                objectPath: "/foo"
                objectName: "bar"
                objectVersion: ""
